const GET_VIDEO_THUMBNAIL = 'video/GET_VIDEO_THUMBNAIL';

const GET_VIDEO_DESCRIPTION = 'video/GET_VIDEO_DESCRIPTION';
const GET_VIDEO_ID = 'user/GET_VIDEO_ID'; //to use in embed url format.
const GET_VIDEO_ID_SUCCESS = 'user/GET_VIDEO_ID_SUCCESS';

export {
  GET_VIDEO_DESCRIPTION,
  GET_VIDEO_THUMBNAIL,
  GET_VIDEO_ID,
  GET_VIDEO_ID_SUCCESS,
};
